### ISSUE TITLE
Deplaying HA4Iot to device on another "private" network

### ISSUE THREAD

**Issue by byrialsen** [chkr1011/HA4IoT#11]
Hi
I am aware that this is more a network related question, but I will try to you @chkr1011 as you might already have some experience with it.
The situation is that in my own setup I have my developer machine and my RPi on the same network. No problem with deploying the system on my device using Remote Machine from Visual Studio.
But I also maintain the code (controllers) to my dad's RPi which is located on his own private network. Using Port-forwarding set up in his router it is possible to access his device from the WAN, but I can't convince myself if there is a way to be able to deploy the code from my developer machine on his RPi directly.
If not are there any other preferrable opportunities like Powershell, VPN etc.

**Comment by byrialsen** [comment]
Looking at it again, I found out how to create an App Package from Visual Studio and I assume that this package can be referenced from the RPi's web interface and installed easily this way. (haven't tried it yet)

But still I need to be able to deploy the web apps also.

**Comment by chkr1011** [comment]
Hi,
I assume that it is not supported. In general only a few ports must be forwarded but for security reasons I would not do it in this way. The commercial version of Windows 10 IoT Core supports the Windows Store where updates are loaded automatically.

So in the end loading the app package manually seems to be the only way to update a "remote" installation at the moment.

Best regards
Christian

**Comment by chkr1011** [comment]
Hi,
do you need more assistance with the deployment or can I close this issue?

Best regards
Christian

**Comment by byrialsen** [comment]
Hi again.

Ya, please close it again.
