### ISSUE TITLE
Web-Project

### ISSUE THREAD

**Issue by Schwenkner** [chkr1011/HA4IoT#14]
Hallo, ich habe vor kurzem auch von diesem Projekt erfahren, super. Selbst habe ich etwas ähnliches implementiert, habe mich aber mehrfach mit dem Design der Services verrannt und immer wieder von vorn begonnen. So ist leider nie etwas endgültiges entstanden.

Nun wollte ich deinen Ansatz ausprobieren, er verspricht mehr Stabilität. Ich möchte aber meine eigene Web-Application erstellen. Kannst du verraten, welche Templates du in VS benutzt hast, um die beiden Projekte WebApp und ManagementApp zu erstellen? Ich finde keine geeigneten. Und alles aus deinen Beispielen heraus kopieren wollte ich erst einmal auch nicht.

Wenn ich dann meine Services umgeschrieben habe, kann ich sie sicherlich hier mit beisteuern.

**Comment by chkr1011** [comment]
Hi,
danke für Dein Interesse an diesem Projekt!

Die WebApp ist etwas umständliches. Ich musste den WebServer für das Projekt selber implementieren weil auf Windows 10 IoT Core kein Webserver bereitsteht. Daher kann man auch kein "echtes" Web-Projekt in VS verwenden und einfach deployen. 

Momentan versuche ich das Projekt als ASP.NET MVC-Projekt in die Cloud (Azure) zu legen um von dort weltweit auf mein System zuzugreifen. Das ist allerdings noch in einer recht frühen Entwicklungsphase. Sieht aber vielversprechend aus. 

Das bedeutet also, dass beide Apps ausschließlich aus HTML, Javascript und CSS bestehen. Wenn Du also deine eigene App bauen möchtest kannst du das auch ohne VS etc. Ich habe jedoch persönlich ein ASP.NET MVC-Projekt in VS verwendet damit ich VS als Editor verwenden kann und ein wenig IntelliSense, Resharper etc. nutzen kann. Durch das Deployment Script werden dann auch nur die Dateien 1zu1 auf den Pi kopiert.

Wenn Du weitere Infos benötigst lass es mich wissen. Auch bei der API helfe ich Dir gerne weiter. Es würde mich freuen wenn Du Deine fertige App diesem Projekt beisteuern würdest.

Aber ich habe noch eine andere Frage: Warum eine eigene App? Was fehlt Dir an der bestehenden? Und warum möchtest Du diese nicht einfach erweitern?

Grüße
Christian

**Comment by Schwenkner** [comment]
Danke für die extrem schnelle Antwort. So eine prompte Reaktion hatte ich nicht erwartet.

Ich habe gesehen, dass du deinen eigenen Web-Server geschrieben hast. Das ist auch bei mir so, mein Ansatz ist ähnlich, ich kann die Routen per Attribute definieren. WebSockets hatte ich auch selbst implementiert. AngularJS sollte auch funktionieren, habe es aber noch nicht versucht. Und statt Bootstrap benutze ich ein anderes kleines Framework. Den Zugriff auf den Http-Server über das Netz hatte ich mit DynDNS bewerkstelligt.

Was die Services betrifft, so hatte ich zunächst die Idee, jeden als eigenständigen UWP-Service zu implementieren, der dann bei Bedarf vom "Controller" gelaunched wird. Leider sind UWP-Services aber keine richtigen Services wie in Windows. Bei jedem Launch wird eine neue Instance gestartet und IoT suspendet sie auch je nach Bedarf,. Eigentlich hatte ich geplant, solche Services als Headless-Application zu implementieren und sie automatisch zu starten. Und der Controller sollte dann mit ihnen Kommunizieren. Das geht aber unter IoT/UWP nicht, weil jedes Mal, wenn man eine Kommunikation mit dem Service aufbaut, dieser neu gestartet wird. So können auch nicht zwei Anwendungen sich einen Service teilen.

Nun zur App. Ich wollte eigentlich nur das Konzept hinter deiner Lösung verstehen. Und nachdem dein Http-Server funktioniert, wollte ich ihn nur eine Hello-World-Seite anzeigen lassen. Dazu habe ich auch ein MVC-Projekt benutzt, habe aber gesehen, dass mir das VS-Template viel mehr generiert, als bei die. Beispielsweise enthält die Web.Config viel mehr Einträge, es gibt Controller, statt Style.css gibt es Site.css und in den Verweisen sind auch etliche cs-Klassen referenziert. Hast du das alles nachträglich manuell geändert? Wenn ja, dann ist es mir klar.

Um deine App zu erweitern, muss ich erst einmal den Ansatz verstehen. Ich beschäftige mich jetzt erst den ersten Tag mit HA4IoT.

Gruß, Wernfried

**Comment by chkr1011** [comment]
Klar, das ist guter Kunden-Support :-) Ich nehme an, das Ticket zu schließen war keine Absicht oder?

WebSockets habe ich auch, aber die nutze ich momentan nicht. Wenn Du in dem Thema fit bist kannst Du Dir die Implementierung gerne einmal ansehen und mir Feedback geben.

Welches Framework nutzt Du? Langfristig wollte ich auf "Semantic UI" wechseln. Das hat ein moderneres Look and Feel als Bootstrap.

DynDns geht bei mir leider nicht weil ich eine DSLite-Anschluss habe. Aber das Feature über die Cloud zu gehen kann ich Dir auch freischalten und Du richtest den Server selber ein.

Das mit den Services klingt sehr interessant. Aber wie kommunizieren die genau? Ich hatte das Problem mit der Network Isolation. Daher können Apps nicht untereinander kommunizieren. Oder gibt es da einen anderen Weg?

Ich hatte glaube ich das "Empty MVC"-Template genommen. Aber ich weiß auch, dass ich mal alles von hand Stück für Stück gelöscht habe was nicht benötigt wurde. Durch die Azure-Geschichte kommt das jetzt aber Stück für Stück alles wieder zurück.

OK, dann schaue Dir alles an. Wenn Du Hilfe benötigst helfe ich gerne weiter. Ich muss die Tage auch noch ein Release fertig machen weil ich noch ein paar kleine Bugs im Zusammenhang mit HTTP etc. gefunden habe. 

Grüße
Christian

**Comment by Schwenkner** [comment]
Sorry für das Schließen des Tickets, war ein Versehen.

Ich habe ein ganz simples [Grid-System ](http://www.responsivegridsystem.com)benutzt, das ist klein und tut, was es soll.

Was die Services betrifft, suche mal nach AppServices. Aber wie gesagt, es gibt immer nur eine Instancce und Windows suspendet sie nach Bedarf. Wenn man beispielsweise einen LogService hat und einen TimerService und den MainService, die beide loggen wollen, dann beendet der eine jeweils die Verbindung für die anderen und instantiiert ihn neu, wodurch eventuell im Speicher gehaltene Messages verloren sind. Man müsste alles persistieren. Ähnlich wie dein 433MHz-Service wollte ich auch einen schreiben, der von verschiedenen anderen Headless-Applikationen benutzt wird. Aber der Service wird jedes mal neu instantiiert und manchmal auch vom OS suspendiert. Dieses Konzept stammt halt aus der App-Philosophie, ist für IoT aber unbrauchbar. Im Creator-Update gibt es da jetzt Änderungen, ich weiß aber nicht, ob es das für IoT gibt.

"Empty MVC" war das Stichwort. Das habe ich mir jetzt mal angesehen, leider gibt es das nicht mehr seit Net.Core und da sieht es auch ganz anders aus als bei dir. Kann es sein, dass es jetzt wieder mit VS 2017 vorhanden ist? Du benutzt ja 2017, ich habe es momentan nicht auf dem Rechner verfügbar, an dem ich sitze.

**Comment by chkr1011** [comment]
Ah OK. Das ist dann natürlich blöd wenn die einfach beendet werden. 

Ich arbeite mit VS2017 seit der aktuellen Version. Die Community Edition reicht dafür vollkommen aus.
Ich hatte das Projekt aber damals mit VS2015 angelegt. Aber es auch, wie gesagt, komplett umgekrempelt und alles MVC-Relevante manuell gelöscht.

Grüße 
Christian
