### ISSUE TITLE
Hallo

### ISSUE THREAD

**Issue by jsp-email** [chkr1011/HA4IoT#5]
Gibt es ne Anleitung wie ich das es auf raspberry installieren kann
Oder ein fertigen image
Lg

**Comment by chkr1011** [comment]
Hi,
eine detaillierte Anleitung gibt es leider noch nicht da ich dazu bisher keine Zeit hatte. Dennoch kann ich die Installation kurz zusammenfassen.

1. Die Solution auf "Debug/ARM (for RaspberryPi)/HA4IoT.Controller.Default" einstellen und kompilieren.
2. Die Code-basierte Konfiguration vornehmen (das Projekt HA4IoT.Controller.Main ist ein Beispiel dafür).
4. Die Debug-Konfiguration auf "Remote Device" konfigurieren (im Verzeichnis \Documentation\QuickStartGuide sind schon einige Screens dazu hinterlegt).
5. Das Projekt starten (wodurch die Anwendung gestartet wird).
6. Über die Funktion "Detach all" den Debugger trennen ohne den Prozess zu beenden (das System läuft jetzt auf dem Pi. Zusätzlich über das Frontend von Windows IoT Core die Anwendung auf "Autostart" konfigurieren damit diese bei jedem Boot automatisch startet).
7. Im Verzeichnis "App" gibt es ein PowerShell script für das Deployment der WebApp. Vor der Ausführung muss der SMB-Share des Pis geöffnet werden da für den Zugriff Credentials erforderlich sind.
8. Über den Link http://[rasperry-pi-address]/App/index.html kann die App geöffnet werden.

Ich empfehle die Verwendung des develop branch da dieser einen sehr großen Umbau enthält der einige breaking changes nach sich zieht und die Management App als HTML app vorliegt anstelle einer WPF app.

Falls es noch Probleme gibt helfe ich gerne weiter.

Grüße
Christian

**Comment by jsp-email** [comment]
hallo
die develop branch bekomme ich nicht an laufen 
problem ich arbeite mit windows 7 hab kein windows 10
die version 1.3... läuft unter visual basic 2015
weiss irgendwie nicht wie das auf pi alles soll. gibt es kein fertiges image oder so
muss win 10 auf raspberry daran scheitert es auch kein win 10 auf pc 
möchte so gerne dein projekt nutzen 
ps hab dich auf facebook angeschrieben gucke mal in nachrichten unter sonstiges 
lg jens

**Comment by BennyBread** [comment]
Hi, ich habe dein Projekt auch per Zufall gefunden. TOLLE Arbeit. Muss man echt sagen!

Ich habe nen RPi3 mit Win100IOT drauf.
Wenn ich nun per Remotedebug session das Projekt starte kommen aber nur exceptions dass er die I2C Slaves nicht findet usw.
Ich habe natürlich keine Slaves dran hängen, wolllte erst mal in das Projekt reinschauen und wenn es funktioniert später meine Rollos damit zu steuern. Bin im Moment dabei eine I/O Platine zu entwickeln
da ich ne menge Rollos habe und auch sonst noch ein paar andere Kleinigkeiten damit machen will

Das Projekt HA4IoT.Controller.Demo gibt es nicht..

Die Webseite (wie oben beschrieben) zeigt leider gar nichts. Ist einfach nur leer.

Was muss ich tun um "mal reinschauen" zu können?
Scheinbar ist es zwingend notwendig genau Deine HarwareConfig zu haben..
Vielleicht kann ich Dir ja evtl. auch helfen beim Progammieren. Melde Dich mal..
PS: Hab ne Anfrage auf Xing gestartet..

**Comment by chkr1011** [comment]
Hi, 

Helfer sind willkommen :-)

Die Doku ist leider etwas obsolete. Wenn du das Projekt testen willst kann ich dir empfehlen den "Local Controller" als "x86" build zu testen. Dieser läuft auf dem local PC. Leider muss man wegen der "Network Isolation" für UWP-Apps den Firewall-Dienst deaktivieren. Die Apps (App & ManagementApp) musst du dann in das angegebene Verzeichnis kopieren. Für Tests auf deinem Pi kannst du den "Default" Controller nehmen. Dieser enthält zwar keine Komponenten aber startet das Subsystem. Für deine Config müsstest du dann ggf. einen eigenen Branch anlegen. Fürs erste wäre der "Local" Controller aber der richtige Einstiegspunkt.

Der "Main" Controller stellt meine persönlich Konfiguration dar. Die kannst du daher eher nur als Beispiel bzw. Referenz betrachten um zu sehen wie die Konfiguration effektiv vorgenommen wird.

Falls du noch Probleme hast helfe ich Dir gerne weiter.

Grüße
Christian

**Comment by chkr1011** [comment]
@BennyBread Kann ich dir mit der Config weiterhelfen? Mit der neuen Version wurden ein paar Dinge wesentlich einfacher.

Grüße
Christian

**Comment by BennyBread** [comment]
@chkr1011 Danke, im Moment bin ich so oben drüber dass ich leider keine Zeit habe irgendwas daheim am PC zu machen. Werde mir aber bei Gelegenheit mal die Vereinfachungen ansehen. 
Gruß, Benny

**Comment by chkr1011** [comment]
Kein Problem. Dann schließe ich dieses Ticket erstmal. Wenn Du dann Fragen hast kannst du dich gerne wieder an mich wenden oder ein Ticket aufmachen.

Grüße
Christian
