### ISSUE TITLE
Z-Wave

### ISSUE THREAD

**Issue by chrisgabr** [chkr1011/HA4IoT#7]
Hi,
bin auf Dein interessantes Projekt zur Homeautomatisierung gestoßen. Ich würde gerne Z-Wave Geräte anbinden. Hast Du hier schon Erfahrungen gesammelt? Sollte die Einbindung prinzipiell möglich sein?

siehe auch: https://developer.microsoft.com/en-us/windows/iot/samples/zwaveadapter

Viele Grüße
Christian

**Comment by chkr1011** [comment]
Hi,
das sollte sehr einfach möglich sein da die Hardware über eine separate Schicht abstrahiert ist. Du findest diverse Klassen wie zum Beispiel "IBinaryStateEndpoint". Die "Hardware-Anbieter" müssen nur dieses minimale Interface für die Steuerung der Hardware implementieren. Die eigentliche Logik sowie App etc. kommen erst einen Layer darüber. Das bedeutet Du müsstest prinzipiell nur diverse "ZWaveBinaryStateEndpoint" etc. implementieren. An Hand der Klasse "CCToolsBoardService" kannst Du sehen wie das funktioniert. Im Project "Controller.Main" (was als Demo dient) kannst Du sehen wie die einzelnen Lampen etc. mit Hilfe der "Endpoints" erzeugt werden.

Möchtest Du die Anbindung in diesem Projekt hinzufügen (Contributen)? 

Falls Du noch Fragen hast helfe ich Dir gerne weiter.

Viele Grüße
Christian

**Comment by chrisgabr** [comment]
Hi,
vielen Dank für die schnelle Antwort. Schaue ich mir mal an. Bei Detailfragen komme ich gerne noch mal auf Dein Unterstützungsangebot zurück. Falls was brauchbares dabei rauskommt, würde ich meine Anbindung zur Verfügung stellen.

Viele Grüße Christian

**Comment by chkr1011** [comment]
Hi,
gibt es schon Neuigkeiten bezüglich der Z-Wave-Integration?

Grüße
Christian

**Comment by chrisgabr** [comment]
Hi,
bin leider aktuell beruflich zu sehr eingespannt und habe hier noch keine Zeit investieren können. Habe auch noch keine ZWave Hardware angeschafft. Allerdings habe ich mittlerweile viele HUE Lampen im Haus verteilt. Wäre hier auch eine  Integration sinvoll?

Viele Grüße 
Christian

**Comment by chkr1011** [comment]
Hi,
klar das wäre auch sinnvoll. Im Prinzip wäre das nur die Implementierung eines ```HueController``` und einer Klasse die ```ILampAdapter``` implementiert.

Falls du weitere Infos benötigst lass es mich wissen :-)

Grüße
Christian

**Comment by chrisgabr** [comment]
Hi,
ich wollte das Projekt "HA4IoT.Controller" mal lokal ausführen. Dabei bekomme ich folgende Fehlermeldung:
Die Windows Store-App "HA4IoT.Controller.Default-uwp_p2wxv0ry6mv8g!App" kann nicht aktiviert werden. Die Aktivierungsanfrage ist mit Fehler "Dieses Programm wurde durch eine Gruppenrichtlinie geblockt. Wenden Sie sich an den Systemadministrator, um weitere Informationen zu erhalten" fehlgeschlagen.

Entwicklermodus für UWP habe ich aktiviert. Ideen? Sollte das möglich sein? Ich habe folgendes (dazu?) gefunden:
https://developer.microsoft.com/en-us/windows/iot/docs/embeddedmode

Viele Grüße
Christian

**Comment by chrisgabr** [comment]
Gibt es ein Beispiel für einen Controller? Wie wäre er einzubinden? Ich hatte gedacht eine Implementierung von ILampAdapter und Ergänzung in der Konfiguration würde ausreichen?

**Comment by chkr1011** [comment]
Hi, 
dieses Projekt kannst du lokal nicht ausführen. Es ist nur für den Pi selber vorgesehen. Damit man es lokal testen kann gibt es den "Simulator". Dieser hat dann auch Test-Aktoren etc. 

Im Ordner Controller/Examples habe ich meine Config "Main" eingecheckt. Die kannst du nicht verwenden wegen der fehlenden Hardware aber du kannst sehen wie das System Stück für Stück konfiguriert wird. 

Deinen neuen ILampAdapter kannst du prima mit dem Simulator testen. Dort einfach eine Lampe ergänzen oder eine vorhandene auf deinen Adapter umbiegen.

In Zukunft soll die ganze Config über das UI laufen aber bis dahin wird noch ein wenig Zeit vergehen :-)

Falls Du noch weiter Infos brauchst lass es mich wissen :-)

Grüße
Christian
